---
layout: post
title:  "Aibiko gem release and migration from Ocra"
date:   2023-08-25 00:00:00 +0800
categories:
  - aibika
  - packaging
author:
  name: Maxim Samsonov
  email: m.samsonov@computer.org
  use_picture: assets
  social_links:
    - https://github.com/maxirmx
excerpt: >-
    Aibika gem to support users of Ocra (One-Click Ruby Application) in a modern environment
---

= Aibika gem

The https://github.com/larsch/ocra[Ocra (One-Click Ruby Application)] tool used to be an excellent solution for distributing Ruby applications on the Windows platform. With OCRA, you could create a self-extracting, self-running executable that contained the Ruby interpreter, application source code, and any additional Ruby libraries or DLLs needed.
However, the authors of OCRA have not supported or updated it since 2020. This has caused numerous issues with newer versions of Ruby and modern anti-virus software.
Although our team is committed to creating a full-fledged Windows port of the https://github.com/tamatebako/tebako[Tebako packager], which provides a user-space mounted-disk experience with minimal intervention, we have decided to publish our enhanced fork of Ocra in the meantime.

Aibika is direct descendant of Ocra and provides the same feature set and parameters.
We have adopted Aibika for Ruby 2.7 through 3.2 and tested it on Windows 2019 and 2022 in https://docs.github.com/actions[GHA environment]

Since our major objective is to support development of https://www.metanorma.org/[Metanorma]  Aibika is now used to build https://github.com/metanorma/packed-mn[Metanorma single binary for Windows].
Migration did not require any changes other then replacemen of call to _ocra_ to calls to _aibika_ in the build scipts.

Ocra did not work with Ruby 3.x and placed restrictions on the version of _rubygems_ that could be used. Aibika released these restrictions without any changes to the packaging script.

= Packaging examples
== Single file

Now let's package a simple Ruby application that uses an external gem.
Our sample application will check validity of png file using https://github.com/metanorma/pngcheck-ruby/tags[pngcheck gem]:

[source, Ruby]
----
require 'bundler'
require 'pngcheck'
exit if defined?(Aibika)

puts 'Enter png file name:'
fn = gets.chomp
status, info = PngCheck.analyze_file(fn)
puts "Status: #{status}, info: #{info}"
----

Note, that the application exits immediately after _require_ in case of packaging that is signalled by _Aibika_ define. This is a good practice in our case because Aibika loads all application files.
If the execution continues the application will wait for input, do processing and generate the output. Normally it can be avoided.
For correct packaging Aibika shall be able to build a list of all application files and dependencies either through require, or by Gemfile or on the command line.

With this source we can do packaging. Let's assume that the file name is sample.rb; bundler, aibika and pngcheck gems are installed already.

[source]
----
aibika sample.rb
----

THis command will produce the package application _sample.exe_ that can be used as planned:

[source, cmd]
----
...
Finished building sample.exe (4434538 bytes)
D:\Projects\10.Projects\aibika demo>sample.exe
Enter png file name:
correct.png
Status: 0, info: OK: correct.png (172x178, 8-bit palette, non-interlaced, 92.4%).
D:\Projects\10.Projects\aibika demo>sample.exe
Enter png file name:
no.png
Status: 5, info: Failed to open no.png: No such file or directory
----

== With Gemfile
Now let's specify dependencies using Gemfile
Our script will change to

[source, Ruby]
----
require 'pngcheck'
exit if defined?(Aibika)

puts 'Enter png file name:'
fn = gets.chomp
status, info = PngCheck.analyze_file(fn)
puts "Status: #{status}, info: #{info}"
----

Note that indirect bundler dependency went to Gemfile:

[source, Ruby]
----
source "https://rubygems.org"

gem "bundler"
gem "pngcheck", ">= 0.3.1"
----

and packaging command is

[source, cmd]
----
aibika --gemfile Gemfile sample.rb
----

Of course, this method works better in case of complex application with dynamically loaded features.

== Other options
Aibika provide numerous options to control packaging. If simple approach does not work please consider
content detecion options as explained in the https://github.com/tamatebako/aibika#readme[readme].
