---
layout: post
title:  "Tebako announces support of packages based on Ruby 3.3 at v0.8.0"
date:   2024-07-25 00:00:00 +0800
categories:
  - tebako
  - packaging
  - Ruby 3.3
author:
  name: Maxim Samsonov
  email: m.samsonov@computer.org
  use_picture: assets
  social_links:
    - https://github.com/maxirmx
excerpt: >-
  Tebako 0.8.0 now provides an option to create packages based on Ruby 3.3.3 and
  3.3.4 on Ubuntu, Alpine, macOS and Windows.
---

= Tebako announces Ruby 3.3 support at v0.8.0

== General

We are thrilled to announce that Tebako now fully supports Ruby 3.3 in the
latest release, v0.8.0.

This expansion means that you can now leverage the power of
https://www.ruby-lang.org/en/news/2024/06/12/ruby-3-3-3-released/[Ruby 3.3.3] and
https://www.ruby-lang.org/en/news/2024/07/09/ruby-3-3-4-released/[Ruby 3.3.4]
as the foundation for Tebako packages, making Tebako even more versatile for
your development needs.

By embracing Ruby 3.3, we ensure that a wider audience can benefit from Tebako's
features, including simplified deployment, enhanced security, and consistent
application performance across different environments.


== A short recap of Tebako

Tebako is a specialized tool designed to streamline the deployment of Ruby
applications with enhanced security and portability. It packages applications
along with their dependencies into a single, self-contained executable,
eliminating the need for external dependencies.

This approach helps mitigate deployment issues related to environment
differences and dependency management, making it easier to ensure that your
application runs smoothly wherever it is deployed.

Tebako offers several key features:

- **Simplified Deployment**: Tebako simplifies the deployment process by
packaging your Ruby application and its dependencies into a single executable.
This eliminates the need to install and configure dependencies on the target
system, reducing the chances of compatibility issues.

- **Enhanced Security**: By bundling your application and its dependencies into
a self-contained executable, Tebako helps protect your code from unauthorized
access and tampering. It ensures that your application runs in a controlled
environment, reducing the risk of security vulnerabilities.

- **Portability**: Tebako enables you to create executable packages that can run
on different operating systems, including Ubuntu, Alpine, macOS, and Windows.
This allows you to deploy your Ruby application consistently across various
environments, without worrying about platform-specific dependencies.


== Contact information

Contact us if you encounter any problems with Tebako, at our issues page:

* https://github.com/tamatebako/tebako/issues

The team is always on the watch for making things easier for Tebako users.

**__Press on__** _with Tebako_!
