---
layout: post
title:  "Tebako version 0.6.0 released"
date:   2024-04-02 00:00:00 +0800
categories:
  - tebako
  - packaging
  - Windows
author:
  name: Maxim Samsonov
  email: m.samsonov@computer.org
  use_picture: assets
  social_links:
    - https://github.com/maxirmx
excerpt: >-
    Tebako version 0.6.0 was released. This version adds support of Windows target to tebako packaging.
---

= Tebako version 0.6.0 features

Tebako is an executable packager. It packages a https://www.ruby-lang.org/[Ruby]
solution with the key idea:

[quote]
____
one Ruby application => one Tebako image
____

Prior to version 0.6.0 Tebako supported packaging for Linux Gnu (Ubuntu), Linux Musl (Alpine Linux) and MacOS platforms.
Recently released version 0.6.0 adds packaging for Windows 2019, Windows 2022 targets using MinGW ucrt64 toolchain.

The simplest approach to setup Tebako packaging environment on Windows is to use Ruby development environment provided by RubyInstaller, for example Ruby+Devkit 3.1.4-1.
Once it is installed use the following commands to install additional packages and Tebako:

[source, sh]
----
  ridk enable ucrt64

  pacman -S git tar bison flex toolchain make cmake
            boost diffutils libevent double-conversion
            fmt glog dlfcn gtest autotools ncurses libyaml

  gem install tebako
----

Tebako Windows support is released with several limitations:
* Only Ruby 3.1.4 is supported
* Gem with native extensions that use advanced or non-standard build systems are not supported yet.
To our knowledge, unsupported gems incluse libmspack and seven_zip_ruby but most likely it is not the full list.

Tebako team plans to address these limitations in the future releases.