name: links

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
      with:
        enablement: true

    - name: Build with Jekyll
      # Outputs to the './_site' directory by default
      run: bundle exec jekyll build --verbose --trace --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production

    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v2
      with:
        args: --base _site/ --verbose --no-progress '_site/**/*.html'
        fail: true

    # - name: Create Issue From File
    #   if: steps.lychee.outputs.exit_code != 0
    #   uses: peter-evans/create-issue-from-file@v5
    #   with:
    #     title: Link Checker Report
    #     content-filepath: ./lychee/out.md
    #     labels: report, automated issue
